include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/gen/**
    - '**/*.g.dart'

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    unawaited_futures: true
    unnecessary_lambdas: true
